# Generated by Django 5.2.11 on 2026-02-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemindHer_app', '0003_grocerylist_inventoryitem_recipe_cookingsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='items',
            field=models.JSONField(default=list, help_text='List of items to buy with quantities'),
        ),
    ]
